In [12]:
from sklearn.feature_extraction.text import CountVectorizer

In [1]:
!python -m spacy download en_core_web_md

     ---------------------------------------- 42.8/42.8 MB 3.0 MB/s eta 0:00:00
[+] Download and installation successful
You can now load the package via spacy.load('en_core_web_md')


2022-10-29 23:25:27.344943: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2022-10-29 23:25:27.345152: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-10-29 23:25:31.364596: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2022-10-29 23:25:31.365399: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cublas64_11.dll'; dlerror: cublas64_11.dll not found
2022-10-29 23:25:31.366245: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cublasLt64_11.dll'; dlerror: cublasLt64_11.dll not found
2022-10-29 23:25:31.367232: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cu

## Bag of words

In [8]:
class Category:
    BOOKS = "BOOKS"
    CLOTHING = "CLOTHING"

train_x = ["i love the book", "this is a great book", "the fit is great", "i love the shoes"]
train_y = [Category.BOOKS, Category.BOOKS, Category.CLOTHING, Category.CLOTHING]

In [18]:
class category: 
    Sport = "Sport"
    Animals = "Animals"
#     Anime = "Anime"
#     Fruits = "Fruits"
        

In [19]:
# X_train = ["I like Naruto", "i love spyxfamily", "the melons are great", "people will buy tangerines"]
# Y_train = [category.Anime, category.Anime, category.Fruits, category.Fruits]

X_train = ["I like Football", "i love Tennis", "the eagles are great", "people are dangerous to Elephants"]
Y_train = [category.Sport, category.Sport, category.Animals, category.Animals]


In [15]:
vectorizer = CountVectorizer (binary=True)
X_train_vector = vectorizer.fit_transform(X_train)
X_train_vector

<4x12 sparse matrix of type '<class 'numpy.int64'>'
	with 13 stored elements in Compressed Sparse Row format>

In [16]:
print (vectorizer.get_feature_names())
print (X_train_vector.toarray())

['are', 'dangerous', 'eagles', 'elephants', 'football', 'great', 'like', 'love', 'people', 'tennis', 'the', 'to']
[[0 0 0 0 1 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 1 0 0]
 [1 0 1 0 0 1 0 0 0 0 1 0]
 [1 1 0 1 0 0 0 0 1 0 0 1]]


In [20]:
from sklearn import svm


clf = svm.SVC(kernel = 'linear')
clf.fit(X_train_vector, Y_train)

SVC(kernel='linear')

In [21]:
X_test = vectorizer.transform([' Lions are dangerous to'])

In [22]:
clf.predict(X_test)

array(['Animals'], dtype='<U7')

# Word Vectors 

In [23]:
import spacy
import numpy as np 
nlp = spacy.load("en_core_web_md")

In [24]:
print (X_train)

['I like Football', 'i love Tennis', 'the eagles are great', 'people are dangerous to Elephants']


In [25]:
# vectors = ([nlp(text) for text in X_train])
# # print (vectors[0].vector)
# X_train_word_vectors = [x.vector for x in vectors]

In [26]:
vectors = ([nlp(text) for text in train_x])
# print (vectors[0].vector)
X_train_word_vectors = [x.vector for x in vectors]

In [27]:
# clf_wv = svm.SVC(kernel = 'linear')
# clf_wv.fit(X_train_word_vectors, Y_train)

In [28]:
clf_wv = svm.SVC(kernel = 'linear')
clf_wv.fit(X_train_word_vectors, train_y)

SVC(kernel='linear')

In [29]:
test = [" i like a story"]
test_doc = [nlp(text) for text in test]
test_in_word_vectors = [x.vector for x in test_doc]


In [30]:
clf_wv.predict(test_in_word_vectors)

array(['BOOKS'], dtype='<U8')

# Regex

In [31]:
import re

regexp = re.compile(r"^ab[^\s]*cd$")

phrases = ["abcd", 'XXX', 'abxxxxxcd', 'ab cd']

matches = []
for phrase in phrases:
     if re.match(regexp, phrase):
            matches.append(phrase)

print(matches)

['abcd', 'abxxxxxcd']


In [32]:
import re 

regexp = re.compile(r"anime|\bread|story|weather")

test_phrases = ["i watched that anime", 'i am breading this book', 'this weather is so cool']

matches = []

for phrase in test_phrases:
    if re.search(regexp, phrase):
            matches.append(phrase)
            
print (matches)

['i watched that anime', 'this weather is so cool']


# Stemming and Lematizations
technique to normalize the text

In [33]:
!pip install nltk 

In [34]:
import nltk

nltk.download('wordnet')
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Acer\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Acer\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Acer\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [35]:
from nltk.tokenize import word_tokenize 
from nltk.stem import PorterStemmer

stemmer = PorterStemmer()

phrase = 'reading the books'
word_tokens = word_tokenize(phrase)
print (word_tokens)
stemmed_words = []
for word in word_tokens:
    stemmer.stem(word)
    stemmed_words.append(stemmer.stem(word))

" ".join(stemmed_words)

['reading', 'the', 'books']


'read the book'

In [36]:
sent = "cats running ran cactus cactuses cacti community communities"

port = PorterStemmer()
porter = []
for i in sent.split(): 
    port.stem(i)
    porter.append(port.stem(i))
" ".join(porter)


'cat run ran cactu cactus cacti commun commun'

In [37]:
stems = PorterStemmer()
documents = ["Human machine interface for lab abc computer applications",
             "A survey of user opinion of computer system response time",
             "The EPS user interface management system",
             "System and human system engineering testing of EPS",
             "Relation of user perceived response time to error measurement",
             "The generation of random binary unordered trees",
             "The intersection graph of paths in trees",
             "Graph minors IV Widths of trees and well quasi ordering",
             "Graph minors A survey"]

documents = [[stems.stem(word) for word in sentence.split(" ")] for sentence in documents]
# documents = [stem(word) for sentence in documents for word in sentence.split(" ")]
print (documents)
# " ".join(sentence)[for sentence in documents]

[['human', 'machin', 'interfac', 'for', 'lab', 'abc', 'comput', 'applic'], ['a', 'survey', 'of', 'user', 'opinion', 'of', 'comput', 'system', 'respons', 'time'], ['the', 'ep', 'user', 'interfac', 'manag', 'system'], ['system', 'and', 'human', 'system', 'engin', 'test', 'of', 'ep'], ['relat', 'of', 'user', 'perceiv', 'respons', 'time', 'to', 'error', 'measur'], ['the', 'gener', 'of', 'random', 'binari', 'unord', 'tree'], ['the', 'intersect', 'graph', 'of', 'path', 'in', 'tree'], ['graph', 'minor', 'iv', 'width', 'of', 'tree', 'and', 'well', 'quasi', 'order'], ['graph', 'minor', 'a', 'survey']]


## Lemmatizer

In [41]:
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()
phrase = "reading the books"
words = word_tokenize(phrase)

lemmatized_words = []
for word in words:
      lemmatized_words.append(lemmatizer.lemmatize(word, pos='v'))

" ".join(lemmatized_words)

'read the book'

In [42]:
# nltk.download()

In [43]:
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

phrase = 'reading the books'
word_tokens = word_tokenize(phrase)

lemmatized_words = []
for word in word_tokens:
    lemmatized_words.append(lemmatizer.lemmatize(word, pos='v'))
" ".join(lemmatized_words)

'read the book'

## Stopwords

In [44]:
from nltk.corpus import stopwords

stopwords = stopwords.words(('english'))

phrase = "Here is the a sentence demonstrating the removal of stopwords "
words = word_tokenize(phrase)

filtered_sentence = []
for word in words: 
    if word not in stopwords: 
        filtered_sentence.append(word)
" ".join(filtered_sentence)

'Here sentence demonstrating removal stopwords'

## spell correction, sentiment, & pos tagging

In [47]:
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\Acer\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping taggers\averaged_perceptron_tagger.zip.


True

In [55]:
from textblob import TextBlob

phrase = "thiiis is an rexample"

tb_phrase = TextBlob(phrase)

tb_phrase.correct()
tb_phrase.tags


Sentiment(polarity=-1.0, subjectivity=1.0)

In [62]:
from textblob import TextBlob
phrase = "the burger was great"

tb_phrase = TextBlob(phrase)

tb_phrase.sentiment

Sentiment(polarity=0.8, subjectivity=0.75)

# Transformer architecture 

## Setup

In [81]:
!pip install spacy-transformers


In [86]:
!spacy download en_core_web_trf

     -------------------------------------- 460.3/460.3 MB 2.8 MB/s eta 0:00:00

2022-10-30 01:21:26.345245: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2022-10-30 01:21:26.345357: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-10-30 01:21:28.079986: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2022-10-30 01:21:28.080748: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cublas64_11.dll'; dlerror: cublas64_11.dll not found
2022-10-30 01:21:28.081490: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cublasLt64_11.dll'; dlerror: cublasLt64_11.dll not found
2022-10-30 01:21:28.082262: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cu


[+] Download and installation successful
You can now load the package via spacy.load('en_core_web_trf')


In [88]:
import spacy
import torch

nlp = spacy.load("en_core_web_trf")
doc = nlp("Here is some text to encode.")

ValueError: [E002] Can't find factory for 'transformer' for language English (en). This usually happens when spaCy calls `nlp.create_pipe` with a custom component name that's not registered on the current language class. If you're using a Transformer, make sure to install 'spacy-transformers'. If you're using a custom component, make sure you've added the decorator `@Language.component` (for function components) or `@Language.factory` (for class components).

Available factories: attribute_ruler, tok2vec, merge_noun_chunks, merge_entities, merge_subtokens, token_splitter, doc_cleaner, parser, beam_parser, lemmatizer, trainable_lemmatizer, entity_linker, ner, beam_ner, entity_ruler, tagger, morphologizer, senter, sentencizer, textcat, spancat, future_entity_ruler, span_ruler, textcat_multilabel, en.lemmatizer

In [90]:
class Category:
    BOOKS = "BOOKS"
    BANK = "BANK"

train_x = ["good characters and plot progression", "check out the book", "good story. would recommend", "novel recommendation", "need to make a deposit to the bank", "balance inquiry savings", "save money"]
train_y = [Category.BOOKS, Category.BOOKS, Category.BOOKS, Category.BOOKS, Category.BANK, Category.BANK, Category.BANK]

In [92]:
from sklearn import svm

docs = [nlp(text) for text in train_x]
train_x_vectors = [doc.vector for doc in docs]
clf_svm = svm.SVC(kernel='linear')

clf_svm.fit(train_x_vectors, train_y)

test_x = ["i need to write a check"]
docs = [nlp(text) for text in test_x]
test_x_vectors = [doc.vector for doc in docs]

clf_svm.predict(test_x_vectors)

array(['BANK'], dtype='<U5')